Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
hd0.waveder = Waveder.from_binary(dir0 / "WAVEDER")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m hd0[38;5;241m.[39mwaveder [38;5;241m=[39m [43mWaveder[49m[38;5;241;43m.[39;49m[43mfrom_binary[49m[43m([49m[43mdir0[49m[43m [49m[38;5;241;43m/[39;49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mWAVEDER[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/pymatgen/io/vasp/outputs.py:5579[0m, in [0;36mWaveder.from_binary[0;34m(cls, filename, data_type)[0m
[1;32m   5566[0m [38;5;129m@classmethod[39m
[1;32m   5567[0m [38;5;28;01mdef[39;00m [38;5;21mfrom_binary[39m([38;5;28mcls[39m, filename, data_type[38;5;241m=[39m[38;5;124m"[39m[38;5;124mcomplex64[39m[38;5;124m"[39m):
[1;32m   5568[0m     [38;5;124;03m"""Read the WAVEDER file and returns a Waveder object.[39;00m
[1;32m   5569[0m 
[1;32m   5570[0m [38;5;124;03m    Args:[39;00m
[0;32m   (...)[0m
[1;32m   5577[0m [38;5;124;03m        Waveder object.[39;00m
[1;32m   5578[0m [38;5;124;03m    """[39;00m
[0;32m-> 5579[0m     [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m [38;5;28;01mas[39;00m fp:
[1;32m   5581[0m         [38;5;28;01mdef[39;00m [38;5;21mreadData[39m(dtype):
[1;32m   5582[0m             [38;5;124;03m"""[39;00m
[1;32m   5583[0m [38;5;124;03m            Read records from Fortran binary file[39;00m
[1;32m   5584[0m [38;5;124;03m            and convert to np.array of given dtype.[39;00m
[1;32m   5585[0m [38;5;124;03m            """[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../../../tests/test_files/v_Ga/ccd_0_-1/1/WAVEDER'
FileNotFoundError: [Errno 2] No such file or directory: '../../../tests/test_files/v_Ga/ccd_0_-1/1/WAVEDER'

