Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
dir0 = TEST_FILES / "ccd_0_-1" / "optics"
hd0 = HarmonicDefect.from_directories(directories=[dir0])
print(f"The defect band is {hd0.defect_band}")
print(f"The vibrational frequency is omega={hd0.omega} in this case is gibberish.")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[3], line 2[0m
[1;32m      1[0m dir0 [38;5;241m=[39m TEST_FILES [38;5;241m/[39m [38;5;124m"[39m[38;5;124mccd_0_-1[39m[38;5;124m"[39m [38;5;241m/[39m [38;5;124m"[39m[38;5;124moptics[39m[38;5;124m"[39m
[0;32m----> 2[0m hd0 [38;5;241m=[39m [43mHarmonicDefect[49m[38;5;241;43m.[39;49m[43mfrom_directories[49m[43m([49m[43mdirectories[49m[38;5;241;43m=[39;49m[43m[[49m[43mdir0[49m[43m][49m[43m)[49m
[1;32m      3[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe defect band is [39m[38;5;132;01m{[39;00mhd0[38;5;241m.[39mdefect_band[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m      4[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe vibrational frequency is omega=[39m[38;5;132;01m{[39;00mhd0[38;5;241m.[39momega[38;5;132;01m}[39;00m[38;5;124m in this case is gibberish.[39m[38;5;124m"[39m)

File [0;32m~/work/pymatgen-analysis-defects/pymatgen-analysis-defects/pymatgen/analysis/defects/ccd.py:276[0m, in [0;36mHarmonicDefect.from_directories[0;34m(cls, directories, charge_state, relaxed_index, defect_band, store_bandstructure, get_band_structure_kwargs, **kwargs)[0m
[1;32m    274[0m [38;5;28;01mif[39;00m charge_state [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    275[0m     [38;5;28;01mif[39;00m vaspruns[min_idx][38;5;241m.[39mfinal_structure[38;5;241m.[39m_charge [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 276[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    277[0m             [38;5;124m"[39m[38;5;124mCharge state is not provided and cannot be parsed from the POTCAR.[39m[38;5;124m"[39m
[1;32m    278[0m         )
[1;32m    279[0m     charge_state [38;5;241m=[39m vaspruns[[38;5;241m0[39m][38;5;241m.[39mfinal_structure[38;5;241m.[39mcharge
[1;32m    281[0m [38;5;28;01mif[39;00m [38;5;28many[39m(v[38;5;241m.[39mfinal_structure[38;5;241m.[39mcharge [38;5;241m!=[39m charge_state [38;5;28;01mfor[39;00m v [38;5;129;01min[39;00m vaspruns):

[0;31mValueError[0m: Charge state is not provided and cannot be parsed from the POTCAR.

